<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $imageObject = $block->getImage($block->getProduct(), 'product_base_image'); ?>

<div class="catalog-product-view-tab-make-style">
    <h2><?php echo $block->escapeHtml(__('My new style')) ?></h2>
    <div class="actions dropdown example-dropdown-5">
            <span class="action toggle" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" aria-haspopup="true">
        <span>Dropdown</span>
    </span>
        <ul class="dropdown">
            <li>
                <span class="item">One</span>
            </li>
            <li>
                <span class="item">Two</span>
            </li>
            <li>
                <span class="item">Three</span>
            </li>
        </ul>
    </div>
</div>