<?php
declare(strict_types=1);
//use \RecursiveIteratorIterator;

namespace a_Class;

class Foo
{
    public function whoAmI()
    {
//        echo sprintf('Hi, i\'m %s', self::class) . "\n";
//        echo get_class_methods(self::class) . "\n";

        $path = realpath('/misc/apps/magento-226/app/code/Ludmila/LSNewClasses');

        $objects = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path), RecursiveIteratorIterator::SELF_FIRST);
        foreach($objects as $name => $object){
            echo "$name\n";
        }

    }
}
// This is object
$foo1 = new Foo();
$foo1->whoAmI();
