<?php

namespace Ludmila\LSNewClasses\Model;

class ShowFiles
{
    public function show()
    {
        $path = realpath('/misc/apps/magento-226/app/code/Ludmila/LSNewClasses');

//        $objects = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path), RecursiveIteratorIterator::SELF_FIRST);
        $objects = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($path), \RecursiveIteratorIterator::SELF_FIRST);
        foreach($objects as $name => $object){
            echo "$name"." was modified on ".date('F d Y H:i:s',filemtime($name))."\n";
        }
    }
}

$foo1 = new ShowFiles();
$foo1->show();
