<?php
namespace Ludmila\LSNewClasses\Model;

class showTypes
{

    public $typeString;
    public $typeObject;
    public $typeBoolean;
    public $typeNumber;
    public $typeInit;
    public $typeConst;
    public $typeNull;
    public $typeArray;

    public function __construct($typeString, $typeObject, $typeBoolean, $typeNumber, $typeInit, $typeConst, $typeNull, $typeArray)
    {
        $this->typeString = $typeString;
        $this->typeObject = $typeObject;
        $this->typeBoolean = $typeBoolean;
        $this->typeNumber = $typeNumber;
        $this->typeInit = $typeInit;
        $this->typeConst = $typeConst;
        $this->typeNull = $typeNull;
        $this->typeArray = $typeArray;
    }

    public function getArgs()
    {
        return get_object_vars($this);
    }

}