<?php /** @var $block \Magento\Catalog\Block\Product\View */ ?>
<?php $imageObject = $block->getImage($block->getProduct(), 'product_base_image'); ?>
<div class="catalog-product-view-tab-ask-question-form">
    <h2><?= $block->escapeHtml(__('Ask your question')) ?></h2>
    <div>
        <form class="form ask-question"
              action="<?= $block->escapeUrl($block->getUrl('ask_question/submit')) ?>"
              id="ask-question-form"
              method="post"
              data-mage-init='{"ludmila_askQuestion":{}}'
              onsubmit="return false;"
        >
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="name">
                        <span><?= $block->escapeHtml(__('Name')) ?></span>
                    </label>
                    <div class="control">
                        <input name="name"
                               id="name"
                               title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                               class="input-text" type="text"
                               data-validate="{required:true}"
                        />
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email">
                        <span><?= $block->escapeHtml(__('Email')) ?></span>
                    </label>
                    <div class="control">
                        <input name="email"
                               id="email"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('you@example.com')) ?>"
                               class="input-text"
                               type="email"
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </div>
                </div>
                <div class="field phone">
                    <label class="label" for="phone">
                        <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
                    </label>
                    <div class="control">
                        <input name="phone"
                               id="phone"
                               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('+38000-000-00-00')) ?>"
                               class="input-text"
                               type="text"
                               data-validate="{required:true, 'minlength':13, 'maxlength':13, 'mobileUA':true}"
                        />
                    </div>
                </div>
                <div class="field question required">
                    <label class="label" for="question">
                        <span><?= $block->escapeHtml(__('Your question')) ?></span>
                    </label>
                    <div class="control">
                        <textarea name="question"
                                  id="question"
                                  title="<?= $block->escapeHtmlAttr(__('Your question?')) ?>"
                                  placeholder="<?= $block->escapeHtmlAttr(__('Enter your question here')) ?>"
                                  class="input-text"
                                  cols="5" rows="3"
                                  data-validate="{required:true}"
                        ></textarea>
                    </div>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">

                    <input type="hidden" name="sku" value="<?php $block->escapeHtml($product->getSku()) ?>"/>

                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <button type="submit" title="<?= $block->escapeHtmlAttr(__('Send question')) ?>" class="action submit primary">
                        <span><?= $block->escapeHtml(__('Send question')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>