<?php if($block->getData('block_id')): ?>
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($block->getData('block_id'))->toHtml();?>
<?php endif; ?>
<?php if($block->getData('title')): ?>
    <div class="block-button">
        <button class="action button-link"
                onclick="location.href='/geekhub-cms'"
                type="button">
            <span><?php echo $block->getData('title'); ?></span>
        </button>
    </div>

<?php endif; ?>



