<div>
    <a href="#" id="dealer_reg">Registration for dealer</a>
</div>

<div id="reg_popup" style="display:none;">
    <div id="reg_popup_wrapper">
    </div>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        $('#reg_popup_wrapper').empty();
                        this.closeModal();
                    }
                }]
            };
            var popup = modal(options, $('#reg_popup'));
            $("#dealer_reg").on('click',function(){
                var modalContent = '<iframe width="1000" height="500"'+
                    'src="https://www.youtube.com/embed/x_fOnUYy3Fw?autoplay=1&ecver=1&rel=0"'+
                    'frameborder="0" gesture="media" allow="autoplay; encrypted-media" allowfullscreen>'+
                    '</iframe>';
                $('#reg_popup_wrapper').html(modalContent);
                $("#reg_popup").modal("openModal");
            });
        }
    );
</script>