<div class="homework11">
    <h2><?php /* @escapeNotVerified */ echo __('Files:')?></h2>
    <?php foreach ($block->giveFileList() as $filename): ?>
        <p><?php echo __('%s was modified on %s:', $filename, date('F d Y H:i:s.', filemtime($filename)) ); ?></p>
    <?php endforeach;?>

    <h2><?php /* @escapeNotVerified */ echo __('Constants:')?></h2>
    <?php foreach ($block->getConstants() as $constant): ?>
        <p><?php echo __($constant); ?></p>
    <?php endforeach;?>

    <h2><?php /* @escapeNotVerified */ echo __('Methods:')?></h2>
    <?php foreach ($block->getMethods() as $method): ?>
        <p><?php echo __($method->name); ?></p>
    <?php endforeach;?>

    <h2><?php /* @escapeNotVerified */ echo __('Types:')?></h2>
    <?php foreach ($block->getParameters() as $parametersName => $parametersValue) :
        if (is_array($parametersValue)) {
            $parametersValue = $parametersValue['instance'] ?? 'array';
        }
        echo $parametersName . ' : ' . $parametersValue . '<br/>';
        ?>
    <?php endforeach; ?>
</div>